wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: LSTM
dataset:
  desc: null
  value: ./spa-eng/spa.txt
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685445825.588748
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 5
      10:
      - 9
